# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='news',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Дата зміни'),
        ),
    ]
