# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161023_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='blog_news_img',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='', upload_to='images/news/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
