# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='main_img',
            field=models.ImageField(upload_to=gallery.models.gallery_path, verbose_name='Обкладинка альбому'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва альбому'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to=gallery.models.img_path, verbose_name='Картинка'),
        ),
    ]
