# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20161120_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбоми'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
