# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='members/avatars/', verbose_name='Аватарка')),
                ('first_name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('sex', models.CharField(choices=[('m', 'Чоловіча'), ('f', 'Жіноча'), ('o', 'Інша')], default='0', max_length=1, verbose_name='Стать')),
                ('birthday', models.DateField(verbose_name='Дата народження')),
                ('height', models.SmallIntegerField(help_text='Зріст вказувати в СМ', validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(230)], verbose_name='Зріст')),
                ('weight', models.SmallIntegerField(help_text='Вагу вказувати в КГ', validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(30)], verbose_name='Вага')),
                ('is_coach', models.BooleanField(default=False, verbose_name='Тренер')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Керівник клубу')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('games', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зіграні ігри')),
            ],
        ),
    ]
